<?php
///////////////////////////////////////////////////////////////
// Paradise ~ centerkey.com/paradise                         //
// GPLv3 ~ Copyright (c) individual contributors to Paradise //
///////////////////////////////////////////////////////////////

// Font Options
// List of Google fonts
// See https://fonts.google.com

$googleFonts = array(
   "Allan",
   "Allerta Stencil",
   "Amatic SC",
   "Anonymous Pro",
   "Arimo",
   "Arvo",
   "Bowlby One SC",
   "Bubblegum Sans",
   "Chango",
   "Cherry Cream Soda",
   "Chewy",
   "Clicker Script",
   "Coda",
   "Corben",
   "Devonshire",
   "Emilys Candy",
   "Ewert",
   "Fascinate Inline",
   "Faster One",
   "Flavors",
   "Fontdiner Swanky",
   "Galindo",
   "Geo",
   "Geostar",
   "Graduate",
   "Gruppo",
   "Homemade Apple",
   "Irish Grover",
   "Jacques Francois Shadow",
   "Josefin Sans",
   "Jura",
   "Just Another Hand",
   "Kenia",
   "Kristi",
   "League Script",
   "Life Savers",
   "Lobster",
   "Londrina Outline",
   "Londrina Solid",
   "Monoton",
   "Mouse Memoirs",
   "Neucha",
   "Old Standard TT",
   "Open Sans",
   "Orbitron",
   "Pacifico",
   "Philosopher",
   "Princess Sofia",
   "Reenie Beanie",
   "Righteous",
   "Rock Salt",
   "Sail",
   "Six Caps",
   "Slackey",
   "Sniglet",
   "Special Elite",
   "Stalemate",
   "Syncopate",
   "Tangerine",
   "UnifrakturMaguntia",
   "Vibur",
   );

?>
