<?php
///////////////////////////////////////////////////////////////
// Paradise ~ centerkey.com/paradise                         //
// GPLv3 ~ Copyright (c) individual contributors to Paradise //
///////////////////////////////////////////////////////////////

// Font Options
// List of Google fonts
// See https://fonts.google.com

$googleFonts = array(
   "Allan",
   "Allerta Stencil",
   "Amatic SC",
   "Anonymous Pro",
   "Arimo",
   "Arvo",
   "Bangers",
   "Bowlby One SC",
   "Bubblegum Sans",
   "Chango",
   "Cherry Cream Soda",
   "Chewy",
   "Clicker Script",
   "Coda",
   "Corben",
   "Creepster",
   "Devonshire",
   "Emilys Candy",
   "Ewert",
   "Fascinate Inline",
   "Faster One",
   "Flavors",
   "Fontdiner Swanky",
   "Freckle Face",
   "Galindo",
   "Geo",
   "Geostar",
   "Graduate",
   "Gruppo",
   "Homemade Apple",
   "Irish Grover",
   "Jacques Francois Shadow",
   "Josefin Sans",
   "Jura",
   "Just Another Hand",
   "Kenia",
   "Kranky",
   "Kristi",
   "League Script",
   "Life Savers",
   "Lobster",
   "Londrina Outline",
   "Londrina Solid",
   "Lovers Quarrel",
   "Monoton",
   "Monsieur La Doulaise",
   "Mouse Memoirs",
   "Mystery Quest",
   "Neucha",
   "Old Standard TT",
   "Open Sans",
   "Orbitron",
   "Pacifico",
   "Permanent Marker",
   "Philosopher",
   "Princess Sofia",
   "Reenie Beanie",
   "Ribeye",
   "Righteous",
   "Rock Salt",
   "Sail",
   "Six Caps",
   "Slackey",
   "Smokum",
   "Sniglet",
   "Snowburst One",
   "Special Elite",
   "Stalemate",
   "Syncopate",
   "Tangerine",
   "UnifrakturMaguntia",
   "Vibur",
   );

?>
